name: meteoo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^6.1.0
  flutter_map_marker_cluster: ^1.3.5
  flutter_native_splash: ^2.4.0
  geolocator: ^11.0.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  image: flutter-logo.png
  color: "42a5f5"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "flutter-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "flutter-logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "flutter-logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "flutter-logo.png"

flutter:
  uses-material-design: true

assets:
  - .env
